export const TOURNAMENTS = {
  leagues: {
  "Belgium - Pro League": [
    { "id": "anderlecht", "name": "RSC Anderlecht", "badge": "assets/badges/Belgium-ProLeague/anderlecht.svg" },
    { "id": "antwerp", "name": "Royal Antwerp", "badge": "assets/badges/Belgium-ProLeague/antwerp.svg" },
    { "id": "beveren", "name": "SK Beveren", "badge": "assets/badges/Belgium-ProLeague/beveren.svg" },
    { "id": "cercle", "name": "Cercle Brugge", "badge": "assets/badges/Belgium-ProLeague/cercle.svg" },
    { "id": "brugge", "name": "Club Brugge", "badge": "assets/badges/Belgium-ProLeague/brugge.svg" },
    { "id": "charleroi", "name": "Sporting Charleroi", "badge": "assets/badges/Belgium-ProLeague/charleroi.svg" },
    { "id": "genk", "name": "KRC Genk", "badge": "assets/badges/Belgium-ProLeague/genk.svg" },
    { "id": "gent", "name": "Gent", "badge": "assets/badges/Belgium-ProLeague/gent.svg" },
    { "id": "kortrijk", "name": "KV Kortrijk", "badge": "assets/badges/Belgium-ProLeague/kortrijk.svg" },
    { "id": "lalouvere", "name": "RAAL La Louvière", "badge": "assets/badges/Belgium-ProLeague/lalouviere.svg" },
    { "id": "leuven", "name": "OH Leuven", "badge": "assets/badges/Belgium-ProLeague/leuven.svg" },
    { "id": "lommel", "name": "Lommel SK", "badge": "assets/badges/Belgium-ProLeague/lommel.svg" },
    { "id": "mechelen", "name": "KV Mechelen", "badge": "assets/badges/Belgium-ProLeague/mechelen.svg" },
    { "id": "sint-truiden", "name": "Sint-Truiden", "badge": "assets/badges/Belgium-ProLeague/sinttruidense.svg" },
    { "id": "standard-liege", "name": "Standard Liège", "badge": "assets/badges/Belgium-ProLeague/standardliege.svg" },
    { "id": "union-saint-gilloise", "name": "Union Saint-Gilloise", "badge": "assets/badges/Belgium-ProLeague/usg.svg" },
    { "id": "westerlo", "name": "Westerlo", "badge": "assets/badges/Belgium-ProLeague/westerlo.svg" },
    { "id": "zulte-waregem", "name": "Zulte Waregem", "badge": "assets/badges/Belgium-ProLeague/zulte.svg" }
  ],
  "Brazil - Campeonato Brasileiro Série A": [
    { "id": "atletico-mg", "name": "Atlético-MG", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/atleticomg.svg" },
    { "id": "bahia", "name": "Bahia", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/bahia.svg" },
    { "id": "botafogo", "name": "Botafogo FR", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/botafogo.svg" },
    { "id": "cap", "name": "Athletico Paranaense", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/paranaense.svg" },
    { "id": "chapoecoense", "name": "Chapecoense", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/chapecoense.svg" },
    { "id": "corinthians", "name": "Corinthians", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/corinthians.svg" },
    { "id": "coritiba", "name": "Coritiba", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/coritiba.svg" },
    { "id": "cruzeiro", "name": "Cruzeiro EC", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/cruzeiro.svg" },
    { "id": "flamengo", "name": "Flamengo", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/flamengo.svg" },
    { "id": "fluminense", "name": "Fluminense", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/fluminense.svg" },
    { "id": "gremio", "name": "Grêmio", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/gremio.svg" },
    { "id": "internacional", "name": "Internacional", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/internacional.svg" },
    { "id": "mirassol", "name": "Mirassol", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/mirassol.svg" },
    { "id": "palmeiras", "name": "Palmeiras", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/palmeiras.svg" },
    { "id": "rbbragantino", "name": "RB Bragantino", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/bragantino.svg" },
    { "id": "remo", "name": "Remo", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/remo.svg" },
    { "id": "santos", "name": "Santos", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/santos.svg" },
    { "id": "sao paulo", "name": "São Paulo", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/saopaulo.svg" },
    { "id": "vascodagama", "name": "Vasco da Gama", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/vascodagama.svg" },
    { "id": "vitoria", "name": "Vitória", "badge": "assets/badges/Brazil-CampeonatoBrasileiroSerieA/vitoria.svg" }
  ],
  "England - Premier League": [
    { "id": "arsenal", "name": "Arsenal", "badge": "assets/badges/England-PremierLeague/arsenal.svg" },
    { "id": "astonvilla", "name": "Aston Villa", "badge": "assets/badges/England-PremierLeague/astonvilla.svg" },
    { "id": "bournemouth", "name": "Bournemouth", "badge": "assets/badges/England-PremierLeague/bournemouth.svg" },
    { "id": "brentford", "name": "Brentford", "badge": "assets/badges/England-PremierLeague/brentford.svg" },
    { "id": "brighton", "name": "Brighton", "badge": "assets/badges/England-PremierLeague/brighton.svg" },
    { "id": "chelsea", "name": "Chelsea", "badge": "assets/badges/England-PremierLeague/chelsea.svg" },
    { "id": "coventry", "name": "Coventry City", "badge": "assets/badges/England-PremierLeague/coventry.svg" },
    { "id": "palace", "name": "Crystal Palace", "badge": "assets/badges/England-PremierLeague/palace.svg" },
    { "id": "everton", "name": "Everton", "badge": "assets/badges/England-PremierLeague/everton.svg" },
    { "id": "fulham", "name": "Fulham", "badge": "assets/badges/England-PremierLeague/fulham.svg" },
    { "id": "hull", "name": "Hull City", "badge": "assets/badges/England-PremierLeague/hull.svg" },
    { "id": "ipswich", "name": "Ipswich Town", "badge": "assets/badges/England-PremierLeague/ipswich.svg" },
    { "id": "leeds", "name": "Leeds United", "badge": "assets/badges/England-PremierLeague/leeds.svg" },
    { "id": "liverpool", "name": "Liverpool", "badge": "assets/badges/England-PremierLeague/liverpool.svg" },
    { "id": "mancity", "name": "Manchester City", "badge": "assets/badges/England-PremierLeague/mancity.svg" },
    { "id": "manutd", "name": "Manchester United", "badge": "assets/badges/England-PremierLeague/manutd.svg" },
    { "id": "newcastle", "name": "Newcastle United", "badge": "assets/badges/England-PremierLeague/newcastle.svg" },
    { "id": "forest", "name": "Nottingham Forest", "badge": "assets/badges/England-PremierLeague/forest.svg" },
    { "id": "sunderland", "name": "Sunderland", "badge": "assets/badges/England-PremierLeague/sunderland.svg" },
    { "id": "spurs", "name": "Tottenham Hotspur", "badge": "assets/badges/England-PremierLeague/spurs.svg" }
  ],
  "England - EFL Championship": [
    { "id": "birmingham", "name": "Birmingham City", "badge": "assets/badges/England-Championship/birmingham.svg" },
    { "id": "blackburn", "name": "Blackburn Rovers", "badge": "assets/badges/England-Championship/blackburn.svg" },
    { "id": "bolton", "name": "Bolton Wanderers", "badge": "assets/badges/England-Championship/bolton.svg" },
    { "id": "bristol", "name": "Bristol City", "badge": "assets/badges/England-Championship/bristol.svg" },
    { "id": "burnley", "name": "Burnley", "badge": "assets/badges/England-Championship/burnley.svg" },
    { "id": "cardiff", "name": "Cardiff City", "badge": "assets/badges/England-Championship/cardiff.svg" },
    { "id": "charlton", "name": "Charlton Athletic", "badge": "assets/badges/England-Championship/charlton.svg" },
    { "id": "derby", "name": "Derby County", "badge": "assets/badges/England-Championship/derby.svg" },
    { "id": "lincoln", "name": "Lincoln City", "badge": "assets/badges/England-Championship/lincoln.svg" },
    { "id": "middlesbrough", "name": "Middlesbrough", "badge": "assets/badges/England-Championship/middlesbrough.svg" },
    { "id": "millwall", "name": "Millwall", "badge": "assets/badges/England-Championship/millwall.svg" },
    { "id": "norwich", "name": "Norwich City", "badge": "assets/badges/England-Championship/norwich.svg" },
    { "id": "portsmouth", "name": "Portsmouth", "badge": "assets/badges/England-Championship/portsmouth.svg" },
    { "id": "preston", "name": "Preston North End", "badge": "assets/badges/England-Championship/preston.svg" },
    { "id": "qpr", "name": "Queens Park Rangers", "badge": "assets/badges/England-Championship/qpr.svg" },
    { "id": "sheffield", "name": "Sheffield", "badge": "assets/badges/England-Championship/sheffield.svg" },
    { "id": "southampton", "name": "Southampton", "badge": "assets/badges/England-Championship/southampton.svg" },
    { "id": "stoke", "name": "Stoke City", "badge": "assets/badges/England-Championship/stoke.svg" },
    { "id": "swansea", "name": "Swansea City", "badge": "assets/badges/England-Championship/swansea.svg" },
    { "id": "watford", "name": "Watford", "badge": "assets/badges/England-Championship/watford.svg" },
    { "id": "westbrom", "name": "West Bromwich Albion", "badge": "assets/badges/England-Championship/westbrom.svg" },
    { "id": "westham", "name": "West Ham United", "badge": "assets/badges/England-Championship/westham.svg" },
    { "id": "wolves", "name": "Wolverhampton Wanderers", "badge": "assets/badges/England-Championship/wolves.svg" },
    { "id": "wrexham", "name": "Wrexham", "badge": "assets/badges/England-Championship/wrexham.svg" }
  ],
  "France - Ligue 1": [
    { "id": "angers", "name": "Angers SCO", "badge": "assets/badges/France-Ligue1/angers.svg" },
    { "id": "auxerre", "name": "AJ Auxerre", "badge": "assets/badges/France-Ligue1/auxerre.svg" },
    { "id": "brest", "name": "Stade Brestois", "badge": "assets/badges/France-Ligue1/brest.svg" },
    { "id": "lehavre", "name": "Le Havre AC", "badge": "assets/badges/France-Ligue1/lehavre.svg" },
    { "id": "lemans", "name": "Le Mans", "badge": "assets/badges/France-Ligue1/lemans.svg" },
    { "id": "lens", "name": "RC Lens", "badge": "assets/badges/France-Ligue1/lens.svg" },
    { "id": "lille", "name": "Lille OSC", "badge": "assets/badges/France-Ligue1/lille.svg" },
    { "id": "lorient", "name": "Lorient", "badge": "assets/badges/France-Ligue1/lorient.svg" },
    { "id": "lyon", "name": "Lyon", "badge": "assets/badges/France-Ligue1/lyon.svg" },
    { "id": "marseille", "name": "Marseille", "badge": "assets/badges/France-Ligue1/marseille.svg" },
    { "id": "monaco", "name": "AS Monaco", "badge": "assets/badges/France-Ligue1/monaco.svg" },
    { "id": "nice", "name": "OGC Nice", "badge": "assets/badges/France-Ligue1/nice.svg" },
    { "id": "paris", "name": "Paris FC", "badge": "assets/badges/France-Ligue1/paris.svg" },
    { "id": "psg", "name": "Paris Saint-Germain", "badge": "assets/badges/France-Ligue1/psg.svg" },
    { "id": "rennes", "name": "Stade Rennais", "badge": "assets/badges/France-Ligue1/rennes.svg" },
    { "id": "strasbourg", "name": "RC Strasbourg", "badge": "assets/badges/France-Ligue1/strasbourg.svg" },
    { "id": "toulouse", "name": "Toulouse FC", "badge": "assets/badges/France-Ligue1/toulouse.svg" },
    { "id": "troyes", "name": "Troyes", "badge": "assets/badges/France-Ligue1/troyes.svg" }
  ],
  "Germany - Bundesliga": [
    { "id": "augsburg", "name": "FC Augsburg", "badge": "assets/badges/Germany-Bundesliga/augsburg.svg" },
    { "id": "bayern", "name": "Bayern Munich", "badge": "assets/badges/Germany-Bundesliga/bayern.svg" },
    { "id": "bremen", "name": "Werder Bremen", "badge": "assets/badges/Germany-Bundesliga/bremen.svg" },
    { "id": "dortmund", "name": "Borussia Dortmund", "badge": "assets/badges/Germany-Bundesliga/dortmund.svg" },
    { "id": "elversberg", "name": "Elversberg", "badge": "assets/badges/Germany-Bundesliga/elversberg.svg" },
    { "id": "frankfurt", "name": "Eintracht Frankfurt", "badge": "assets/badges/Germany-Bundesliga/frankfurt.svg" },
    { "id": "freiburg", "name": "SC Freiburg", "badge": "assets/badges/Germany-Bundesliga/freiburg.svg" },
    { "id": "gladbach", "name": "Mönchengladbach", "badge": "assets/badges/Germany-Bundesliga/gladbach.svg" },
    { "id": "hamburger", "name": "Hamburger SV", "badge": "assets/badges/Germany-Bundesliga/hamburger.svg" },
    { "id": "hoffenheim", "name": "TSG Hoffenheim", "badge": "assets/badges/Germany-Bundesliga/hoffenheim.svg" },
    { "id": "koln", "name": "1. FC Köln", "badge": "assets/badges/Germany-Bundesliga/koln.svg" },
    { "id": "leipzig", "name": "RB Leipzig", "badge": "assets/badges/Germany-Bundesliga/leipzig.svg" },
    { "id": "leverkusen", "name": "Bayer Leverkusen", "badge": "assets/badges/Germany-Bundesliga/leverkusen.svg" },
    { "id": "mainz", "name": "FSV Mainz 05", "badge": "assets/badges/Germany-Bundesliga/mainz.svg" },
    { "id": "paderborn", "name": "Paderborn", "badge": "assets/badges/Germany-Bundesliga/paderborn.svg" },
    { "id": "schalke", "name": "Schalke 04", "badge": "assets/badges/Germany-Bundesliga/schalke.svg" },
    { "id": "stuttgart", "name": "VfB Stuttgart", "badge": "assets/badges/Germany-Bundesliga/stuttgart.svg" },
    { "id": "unionberlin", "name": "Union Berlin", "badge": "assets/badges/Germany-Bundesliga/unionberlin.svg" }
  ],
  "Italy - Serie A": [
    { "id": "milan", "name": "AC Milan", "badge": "assets/badges/Italy-SerieA/milan.svg" },
    { "id": "atalanta", "name": "Atalanta", "badge": "assets/badges/Italy-SerieA/atalanta.svg" },
    { "id": "bologna", "name": "Bologna", "badge": "assets/badges/Italy-SerieA/bologna.svg" },
    { "id": "cagliari", "name": "Cagliari", "badge": "assets/badges/Italy-SerieA/cagliari.svg" },
    { "id": "como", "name": "Como 1907", "badge": "assets/badges/Italy-SerieA/como.svg" },
    { "id": "fiorentina", "name": "Fiorentina", "badge": "assets/badges/Italy-SerieA/fiorentina.svg" },
    { "id": "frosinone", "name": "Frosinone", "badge": "assets/badges/Italy-SerieA/frosinone.svg" },
    { "id": "genoa", "name": "Genoa", "badge": "assets/badges/Italy-SerieA/genoa.svg" },
    { "id": "inter", "name": "Inter Milan", "badge": "assets/badges/Italy-SerieA/inter.svg" },
    { "id": "juventus", "name": "Juventus", "badge": "assets/badges/Italy-SerieA/juventus.svg" },
    { "id": "lazio", "name": "SS Lazio", "badge": "assets/badges/Italy-SerieA/lazio.svg" },
    { "id": "lecce", "name": "Lecce", "badge": "assets/badges/Italy-SerieA/lecce.svg" },
    { "id": "monza", "name": "Monza", "badge": "assets/badges/Italy-SerieA/monza.svg" },
    { "id": "parma", "name": "Parma Calcio", "badge": "assets/badges/Italy-SerieA/parma.svg" },
    { "id": "roma", "name": "AS Roma", "badge": "assets/badges/Italy-SerieA/roma.svg" },
    { "id": "napoli", "name": "SSC Napoli", "badge": "assets/badges/Italy-SerieA/napoli.svg" },
    { "id": "sassuolo", "name": "Sassuolo", "badge": "assets/badges/Italy-SerieA/sassuolo.svg" },
    { "id": "torino", "name": "Torino FC", "badge": "assets/badges/Italy-SerieA/torino.svg" },
    { "id": "udinese", "name": "Udinese", "badge": "assets/badges/Italy-SerieA/udinese.svg" },
    { "id": "venezia", "name": "Venezia", "badge": "assets/badges/Italy-SerieA/venezia.svg" }
  ],
  "Mexico - Liga MX": [
    { "id": "america", "name": "Club América", "badge": "assets/badges/Mexico-LigaMX/america.svg" },
    { "id": "atlante", "name": "Atlante FC", "badge": "assets/badges/Mexico-LigaMX/atlante.svg" },
    { "id": "atlas", "name": "Atlas FC", "badge": "assets/badges/Mexico-LigaMX/atlas.svg" },
    { "id": "atletico", "name": "Atlético de San Luis", "badge": "assets/badges/Mexico-LigaMX/atletico.svg" },
    { "id": "cruzazul", "name": "Cruz Azul", "badge": "assets/badges/Mexico-LigaMX/cruzazul.svg" },
    { "id": "guadalajara", "name": "CD Guadalajara", "badge": "assets/badges/Mexico-LigaMX/guadalajara.svg" },
    { "id": "juarez", "name": "FC Juárez", "badge": "assets/badges/Mexico-LigaMX/juarez.svg" },
    { "id": "leon", "name": "León", "badge": "assets/badges/Mexico-LigaMX/leon.svg" },
    { "id": "monterrey", "name": "CF Monterrey", "badge": "assets/badges/Mexico-LigaMX/monterrey.svg" },
    { "id": "necaxa", "name": "Club Necaxa", "badge": "assets/badges/Mexico-LigaMX/necaxa.svg" },
    { "id": "pachuca", "name": "CF Pachuca", "badge": "assets/badges/Mexico-LigaMX/pachuca.svg" },
    { "id": "puebla", "name": "Club Puebla", "badge": "assets/badges/Mexico-LigaMX/puebla.svg" },
    { "id": "pumas", "name": "Pumas", "badge": "assets/badges/Mexico-LigaMX/pumas.svg" },
    { "id": "queretaro", "name": "Querétaro FC", "badge": "assets/badges/Mexico-LigaMX/queretaro.svg" },
    { "id": "santos", "name": "Santos Laguna", "badge": "assets/badges/Mexico-LigaMX/santos.svg" },
    { "id": "tigres", "name": "Tigres UANL", "badge": "assets/badges/Mexico-LigaMX/tigres.svg" },
    { "id": "tijuana", "name": "Club Tijuana", "badge": "assets/badges/Mexico-LigaMX/tijuana.svg" },
    { "id": "toluca", "name": "Toluca FC", "badge": "assets/badges/Mexico-LigaMX/toluca.svg" }
  ],
  "Netherlands - Eredivisie": [
    { "id": "ajax", "name": "Ajax", "badge": "assets/badges/Netherlands-Eredivisie/ajax.svg" },
    { "id": "az", "name": "AZ Alkmaar", "badge": "assets/badges/Netherlands-Eredivisie/az.svg" },
    { "id": "cambuur", "name": "SC Cambuur", "badge": "assets/badges/Netherlands-Eredivisie/cambuur.svg" },
    { "id": "denhaag", "name": "ADO Den Haag", "badge": "assets/badges/Netherlands-Eredivisie/denhaag.svg" },
    { "id": "excelsior", "name": "Excelsior", "badge": "assets/badges/Netherlands-Eredivisie/excelsior.svg" },
    { "id": "feyenoord", "name": "Feyenoord", "badge": "assets/badges/Netherlands-Eredivisie/feyenoord.svg" },
    { "id": "fortuna", "name": "Fortuna Sittard", "badge": "assets/badges/Netherlands-Eredivisie/fortuna.svg" },
    { "id": "goahead", "name": "Go Ahead Eagles", "badge": "assets/badges/Netherlands-Eredivisie/goahead.svg" },
    { "id": "groningen", "name": "FC Groningen", "badge": "assets/badges/Netherlands-Eredivisie/groningen.svg" },
    { "id": "heerenveen", "name": "SC Heerenveen", "badge": "assets/badges/Netherlands-Eredivisie/heerenveen.svg" },
    { "id": "nijmegen", "name": "NEC Nijmegen", "badge": "assets/badges/Netherlands-Eredivisie/nijmegen.svg" },
    { "id": "psv", "name": "PSV Eindhoven", "badge": "assets/badges/Netherlands-Eredivisie/psv.svg" },
    { "id": "sparta", "name": "Sparta Rotterdam", "badge": "assets/badges/Netherlands-Eredivisie/sparta.svg" },
    { "id": "telstar", "name": "SC Telstar", "badge": "assets/badges/Netherlands-Eredivisie/telstar.svg" },
    { "id": "twente", "name": "FC Twente", "badge": "assets/badges/Netherlands-Eredivisie/twente.svg" },
    { "id": "utrecht", "name": "FC Utrecht", "badge": "assets/badges/Netherlands-Eredivisie/utrecht.svg" },
    { "id": "willem", "name": "Willem II", "badge": "assets/badges/Netherlands-Eredivisie/willem.svg" },
    { "id": "zwolle", "name": "PEC Zwolle", "badge": "assets/badges/Netherlands-Eredivisie/zwolle.svg" }
  ],
  "Poland - Ekstraklasa": [
    { "id": "cracovia", "name": "Cracovia", "badge": "assets/badges/Poland-Ekstraklasa/cracovia.svg" },
    { "id": "gks", "name": "GKS Katowice", "badge": "assets/badges/Poland-Ekstraklasa/gks.svg" },
    { "id": "gornik", "name": "Górnik Zabrze", "badge": "assets/badges/Poland-Ekstraklasa/gornik.svg" },
    { "id": "jagiellonia", "name": "Jagiellonia Białystok", "badge": "assets/badges/Poland-Ekstraklasa/jagiellonia.svg" },
    { "id": "korona", "name": "Korona Kielce", "badge": "assets/badges/Poland-Ekstraklasa/korona.svg" },
    { "id": "lech", "name": "Lech Poznań", "badge": "assets/badges/Poland-Ekstraklasa/lech.svg" },
    { "id": "legia", "name": "Legia Warszawa", "badge": "assets/badges/Poland-Ekstraklasa/legia.svg" },
    { "id": "motor", "name": "Motor Lublin", "badge": "assets/badges/Poland-Ekstraklasa/motor.svg" },
    { "id": "piast", "name": "Piast Gliwice", "badge": "assets/badges/Poland-Ekstraklasa/piast.svg" },
    { "id": "pogon", "name": "Pogoń Szczecin", "badge": "assets/badges/Poland-Ekstraklasa/pogon.svg" },
    { "id": "radomiak", "name": "Radomiak Radom", "badge": "assets/badges/Poland-Ekstraklasa/radomiak.svg" },
    { "id": "rakow", "name": "Raków Częstochowa", "badge": "assets/badges/Poland-Ekstraklasa/rakow.svg" },
    { "id": "slaska", "name": "Śląsk Wrocław", "badge": "assets/badges/Poland-Ekstraklasa/slask.svg" },
    { "id": "widzew", "name": "Widzew Łódź", "badge": "assets/badges/Poland-Ekstraklasa/widzew.svg" },
    { "id": "wieczysta", "name": "Wieczysta Kraków", "badge": "assets/badges/Poland-Ekstraklasa/wieczysta.svg" },
    { "id": "wislak", "name": "Wisła Kraków", "badge": "assets/badges/Poland-Ekstraklasa/wislak.svg" },
    { "id": "wislap", "name": "Wisła Płock", "badge": "assets/badges/Poland-Ekstraklasa/wislap.svg" },
    { "id": "zaglebie", "name": "Zagłębie Lubin", "badge": "assets/badges/Poland-Ekstraklasa/zaglebie.svg" }
  ],
  "Portugal - Primeira Liga": [
    { "id": "alverca", "name": "FC Alverca", "badge": "assets/badges/Portugal-PrimeiraLiga/alverca.svg" },
    { "id": "academico", "name": "Académico de Viseu FC", "badge": "assets/badges/Portugal-PrimeiraLiga/academico.svg" },
    { "id": "arouca", "name": "FC Arouca", "badge": "assets/badges/Portugal-PrimeiraLiga/arouca.svg" },
    { "id": "benfica", "name": "SL Benfica", "badge": "assets/badges/Portugal-PrimeiraLiga/benfica.svg" },
    { "id": "braga", "name": "SC Braga", "badge": "assets/badges/Portugal-PrimeiraLiga/braga.svg" },
    { "id": "casapia", "name": "Casa Pia AC", "badge": "assets/badges/Portugal-PrimeiraLiga/casapia.svg" },
    { "id": "estrela", "name": "Estrela da Amadora", "badge": "assets/badges/Portugal-PrimeiraLiga/estrela.svg" },
    { "id": "estoril", "name": "Estoril Praia", "badge": "assets/badges/Portugal-PrimeiraLiga/estoril.svg" },
    { "id": "famalicao", "name": "FC Famalicão", "badge": "assets/badges/Portugal-PrimeiraLiga/famalicao.svg" },
    { "id": "gilvicente", "name": "Gil Vicente FC", "badge": "assets/badges/Portugal-PrimeiraLiga/gilvicente.svg" },
    { "id": "maritimo", "name": "CS Marítimo", "badge": "assets/badges/Portugal-PrimeiraLiga/maritimo.svg" },
    { "id": "moreirense", "name": "Moreirense FC", "badge": "assets/badges/Portugal-PrimeiraLiga/moreirense.svg" },
    { "id": "nacional", "name": "CD Nacional", "badge": "assets/badges/Portugal-PrimeiraLiga/nacional.svg" },
    { "id": "porto", "name": "FC Porto", "badge": "assets/badges/Portugal-PrimeiraLiga/porto.svg" },
    { "id": "rioave", "name": "Rio Ave FC", "badge": "assets/badges/Portugal-PrimeiraLiga/rioave.svg" },
    { "id": "santaclara", "name": "Santa Clara", "badge": "assets/badges/Portugal-PrimeiraLiga/santaclara.svg" },
    { "id": "sporting", "name": "Sporting CP", "badge": "assets/badges/Portugal-PrimeiraLiga/sporting.svg" },
    { "id": "vitoria", "name": "Vitória SC", "badge": "assets/badges/Portugal-PrimeiraLiga/vitoria.svg" }
  ],
  "Spain - La Liga": [
    { "id": "alaves", "name": "Alavés", "badge": "assets/badges/Spain-LaLiga/alaves.svg" },
    { "id": "athletic", "name": "Athletic Club", "badge": "assets/badges/Spain-LaLiga/athletic.svg" },
    { "id": "atletico", "name": "Atlético Madrid", "badge": "assets/badges/Spain-LaLiga/atletico.svg" },
    { "id": "barcelona", "name": "FC Barcelona", "badge": "assets/badges/Spain-LaLiga/barcelona.svg" },
    { "id": "betis", "name": "Real Betis", "badge": "assets/badges/Spain-LaLiga/betis.svg" },
    { "id": "celtavigo", "name": "Celta Vigo", "badge": "assets/badges/Spain-LaLiga/celtavigo.svg" },
    { "id": "deportivo", "name": "Deportivo de A Coruña", "badge": "assets/badges/Spain-LaLiga/deportivo.svg" },
    { "id": "elche", "name": "Elche", "badge": "assets/badges/Spain-LaLiga/elche.svg" },
    { "id": "espanyol", "name": "Espanyol", "badge": "assets/badges/Spain-LaLiga/espanyol.svg" },
    { "id": "getafe", "name": "Getafe CF", "badge": "assets/badges/Spain-LaLiga/getafe.svg" },
    { "id": "levante", "name": "Levante", "badge": "assets/badges/Spain-LaLiga/levante.svg" },
    { "id": "malaga", "name": "Malaga", "badge": "assets/badges/Spain-LaLiga/malaga.svg" },
    { "id": "osasuna", "name": "CA Osasuna", "badge": "assets/badges/Spain-LaLiga/osasuna.svg" },
    { "id": "racing", "name": "Racing Santander", "badge": "assets/badges/Spain-LaLiga/racing.svg" },
    { "id": "rayo", "name": "Rayo Vallecano", "badge": "assets/badges/Spain-LaLiga/rayo.svg" },
    { "id": "realmadrid", "name": "Real Madrid", "badge": "assets/badges/Spain-LaLiga/realmadrid.svg" },
    { "id": "sevilla", "name": "Sevilla FC", "badge": "assets/badges/Spain-LaLiga/sevilla.svg" },
    { "id": "sociedad", "name": "Real Sociedad", "badge": "assets/badges/Spain-LaLiga/sociedad.svg" },
    { "id": "valencia", "name": "Valencia CF", "badge": "assets/badges/Spain-LaLiga/valencia.svg" },
    { "id": "villarreal", "name": "Villarreal CF", "badge": "assets/badges/Spain-LaLiga/villarreal.svg" }
  ],
  "Türkiye - Süper Lig": [
    { "id": "alanyaspor", "name": "Alanyaspor", "badge": "assets/badges/Turkiye-SuperLig/alanyaspor.svg" },
    { "id": "amed", "name": "Amedspor", "badge": "assets/badges/Turkiye-SuperLig/amed.svg" },
    { "id": "basaksehir", "name": "Başakşehir", "badge": "assets/badges/Turkiye-SuperLig/basaksehir.svg" },
    { "id": "besiktas", "name": "Beşiktaş", "badge": "assets/badges/Turkiye-SuperLig/besiktas.svg" },
    { "id": "corum", "name": "Çorum FK", "badge": "assets/badges/Turkiye-SuperLig/corum.svg" },
    { "id": "erzurumspor", "name": "Erzurumspor FK", "badge": "assets/badges/Turkiye-SuperLig/erzurumspor.svg" },
    { "id": "eyupspor", "name": "Eyüpspor", "badge": "assets/badges/Turkiye-SuperLig/eyupspor.svg" },
    { "id": "fenerbahce", "name": "Fenerbahçe", "badge": "assets/badges/Turkiye-SuperLig/fenerbahce.svg" },
    { "id": "galatasaray", "name": "Galatasaray", "badge": "assets/badges/Turkiye-SuperLig/galatasaray.svg" },
    { "id": "gaziantep", "name": "Gaziantep FK", "badge": "assets/badges/Turkiye-SuperLig/gaziantep.svg" },
    { "id": "genclerbirligi", "name": "Gençlerbirliği", "badge": "assets/badges/Turkiye-SuperLig/genclerbirligi.svg" },
    { "id": "goztepe", "name": "Göztepe", "badge": "assets/badges/Turkiye-SuperLig/goztepe.svg" },
    { "id": "kasimpasa", "name": "Kasımpaşa", "badge": "assets/badges/Turkiye-SuperLig/kasimpasa.svg" },
    { "id": "kocaelispor", "name": "Kocaelispor", "badge": "assets/badges/Turkiye-SuperLig/kocaelispor.svg" },
    { "id": "konyaspor", "name": "Konyaspor", "badge": "assets/badges/Turkiye-SuperLig/konyaspor.svg" },
    { "id": "rizespor", "name": "Çaykur Rizespor", "badge": "assets/badges/Turkiye-SuperLig/rizespor.svg" },
    { "id": "samsunspor", "name": "Samsunspor", "badge": "assets/badges/Turkiye-SuperLig/samsunspor.svg" },
    { "id": "trabzonspor", "name": "Trabzonspor", "badge": "assets/badges/Turkiye-SuperLig/trabzonspor.svg" }
  ],
  "USA - Major League Soccer": [
    { "id": "atlanta", "name": "Atlanta United FC", "badge": "assets/badges/USA-MajorLeagueSoccer/atlanta.svg" },
    { "id": "austin", "name": "Austin FC", "badge": "assets/badges/USA-MajorLeagueSoccer/austin.svg" },
    { "id": "charlotte", "name": "Charlotte FC", "badge": "assets/badges/USA-MajorLeagueSoccer/charlotte.svg" },
    { "id": "chicagofire", "name": "Chicago Fire FC", "badge": "assets/badges/USA-MajorLeagueSoccer/chicagofire.svg" },
    { "id": "cincinnati", "name": "FC Cincinnati", "badge": "assets/badges/USA-MajorLeagueSoccer/cincinnati.svg" },
    { "id": "colorado", "name": "Colorado Rapids", "badge": "assets/badges/USA-MajorLeagueSoccer/colorado.svg" },
    { "id": "columbus", "name": "Columbus Crew", "badge": "assets/badges/USA-MajorLeagueSoccer/columbus.svg" },
    { "id": "dcunited", "name": "D.C. United", "badge": "assets/badges/USA-MajorLeagueSoccer/dcunited.svg" },
    { "id": "fcdallas", "name": "FC Dallas", "badge": "assets/badges/USA-MajorLeagueSoccer/fcdallas.svg" },
    { "id": "houston", "name": "Houston Dynamo FC", "badge": "assets/badges/USA-MajorLeagueSoccer/houston.svg" },
    { "id": "kansascity", "name": "Sporting Kansas City", "badge": "assets/badges/USA-MajorLeagueSoccer/kansascity.svg" },
    { "id": "lagalaxy", "name": "LA Galaxy", "badge": "assets/badges/USA-MajorLeagueSoccer/lagalaxy.svg" },
    { "id": "lafc", "name": "Los Angeles FC", "badge": "assets/badges/USA-MajorLeagueSoccer/lafc.svg" },
    { "id": "intermiami", "name": "Inter Miami CF", "badge": "assets/badges/USA-MajorLeagueSoccer/intermiami.svg" },
    { "id": "minnesota", "name": "Minnesota United FC", "badge": "assets/badges/USA-MajorLeagueSoccer/minnesota.svg" },
    { "id": "montreal", "name": "CF Montréal", "badge": "assets/badges/USA-MajorLeagueSoccer/montreal.svg" },
    { "id": "nashville", "name": "Nashville SC", "badge": "assets/badges/USA-MajorLeagueSoccer/nashville.svg" },
    { "id": "newengland", "name": "New England Revolution", "badge": "assets/badges/USA-MajorLeagueSoccer/newengland.svg" },
    { "id": "nycfc", "name": "New York City FC", "badge": "assets/badges/USA-MajorLeagueSoccer/nycfc.svg" },
    { "id": "nyredbulls", "name": "New York Red Bulls", "badge": "assets/badges/USA-MajorLeagueSoccer/nyredbulls.svg" },
    { "id": "orlando", "name": "Orlando City SC", "badge": "assets/badges/USA-MajorLeagueSoccer/orlando.svg" },
    { "id": "philadelphia", "name": "Philadelphia Union", "badge": "assets/badges/USA-MajorLeagueSoccer/philadelphia.svg" },
    { "id": "portland", "name": "Portland Timbers", "badge": "assets/badges/USA-MajorLeagueSoccer/portland.svg" },
    { "id": "realsaltlake", "name": "Real Salt Lake", "badge": "assets/badges/USA-MajorLeagueSoccer/realsaltlake.svg" },
    { "id": "sandiego", "name": "San Diego FC", "badge": "assets/badges/USA-MajorLeagueSoccer/sandiego.svg" },
    { "id": "sanjose", "name": "San Jose Earthquakes", "badge": "assets/badges/USA-MajorLeagueSoccer/sanjose.svg" },
    { "id": "seattle", "name": "Seattle Sounders FC", "badge": "assets/badges/USA-MajorLeagueSoccer/seattle.svg" },
    { "id": "stlouis", "name": "St. Louis City SC", "badge": "assets/badges/USA-MajorLeagueSoccer/stlouis.svg" },
    { "id": "toronto", "name": "Toronto FC", "badge": "assets/badges/USA-MajorLeagueSoccer/toronto.svg" },
    { "id": "vancouver", "name": "Vancouver Whitecaps FC", "badge": "assets/badges/USA-MajorLeagueSoccer/vancouver.svg" }
  ]
  },
  worldcup: {
  "Bronze-final": [
    { "id": "england", "name": "England", "badge": "assets/badges/WorldCup2026/england.svg" },
    { "id": "france", "name": "France", "badge": "assets/badges/WorldCup2026/france.svg" }
  ],
  "Final": [
  { "id": "argentina", "name": "Argentina", "badge": "assets/badges/WorldCup2026/argentina.svg" },
  { "id": "spain", "name": "Spain", "badge": "assets/badges/WorldCup2026/spain.svg" }
  ]
  }
};